### ISSUE TITLE
Priority Items - ASAP 

### ISSUE THREAD

**Issue by stevekamps** [technicalbirdVayuz/volleyball-unite-usa-issue-tracker#613]
Items of priority

- [x] #608 – Athlete Search filter not working on app or web 
- [x] #611 – College verify process
- [x] #612 – Blog from dashboard
- [x] #597 – Blog content not showing up on app
- [x] #599 – logo for VU is not clear 
- [x] #594 – Dashboard events creation

**Comment by technicalbirdVayuz** [comment]
For web, shared the updates on the first 3 issues. for App, Update will be shared shortly

**Comment by technicalbirdVayuz** [comment]
Feel Free to open in case any of the mentioned issue persists
